force-app/main/default/objects/Data_Retention_Deletion__mdt/Data_Retention_Deletion__mdt.object-meta.xml
<CustomObject>
    <label>Data Retention Deletion</label>
    <pluralLabel>Data Retention Deletions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Retention_Deletion__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <description>Is the SOQL WHERE clause that is used to select on</description>
    <inlineHelpText>Is the SOQL WHERE clause that is used to select on</inlineHelpText>
    <label>Filter</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataRetentionScheduler.cls
global with sharing class DataRetentionScheduler implements Schedulable{

    private Selector dataRetentionDeletionSelector;

    public DataRetentionScheduler(){
        dataRetentionDeletionSelector = new Selector(Schema.Data_Retention_Deletion__mdt.getSObjectType());
    }

    public DataRetentionScheduler(Selector dataRetentionDeletionSelector){
        this.dataRetentionDeletionSelector = dataRetentionDeletionSelector;
    }

    global void execute(SchedulableContext SC) {
        List<Data_Retention_Deletion__mdt> drds = (List<Data_Retention_Deletion__mdt>)dataRetentionDeletionSelector.queryList();
        List<String> queries = new List<String>();
        for (Data_Retention_Deletion__mdt drd : drds){
            queries.add('SELECT Id FROM ' + drd.Object__c + ' WHERE ' + drd.Filter__c);
        }
        if (queries.size() > 0){
            SObjectDeleter sObjectDeleter = new SObjectDeleter(queries);
            Database.executeBatch(sObjectDeleter);
        }
    }
}